- name: Determine current date
  command: "date --utc +'%Y-%m-%dT%H-%MZ'"
  register: _date_output

- name: Set backup_id fact
  set_fact:
    backup_id: "{{ _date_output.stdout }}"

- name: Set backup_id_path fact (full path to backup directory)
  set_fact:
    backup_id_path: "{{ backup_dir }}/{{ backup_id }}"

- name: Fail if backup directory with same ID already exists
  fail:
    msg: "Backup directory {{ backup_id_path }} already exists. Aborting."
  when: backup_id_path is exists

- name: Create backup directory
  file:
    path: "{{ backup_id_path }}"
    state: directory
    mode: u=rwx,g=,o=

- name: Created backup directory
  debug: msg="Created backup directory {{ backup_id_path }}"
