[package]
name = "opendut-vpn-netbird"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
opendut-types = { workspace = true }
opendut-vpn = { workspace = true }
opendut-util = { workspace = true, features = ["serde"] }

async-trait = { workspace = true }
anyhow = { workspace = true }
http = { workspace = true }
reqwest = { workspace = true, features = ["json"] }
reqwest-middleware = { workspace = true }
reqwest-retry = { workspace = true}
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
thiserror = { workspace = true }
time = { workspace = true, features = ["serde-well-known"] }
tokio = { workspace = true, features = ["full"] }
tracing = { workspace = true }
uuid = { workspace = true, features = ["serde"] }

[dev-dependencies]
googletest = { workspace = true }
mockall = { workspace = true }
rstest = { workspace = true }
test-log = { workspace = true }
test-with = { workspace = true }

[lints]
workspace = true
