- name: Determine available backups
  ansible.builtin.shell:
    cmd: ls {{ backup_dir }}
  register: _present_backups

- name: Show backups
  debug: msg="{{ _present_backups.stdout_lines }}"

- name: Define latest backup if no backup_id provided
  set_fact:
    backup_id: "{{ _present_backups.stdout_lines | last }}"
  when: backup_id is not defined  # will be overwritten by extra variables anyway but check for extra caution
# see also https://docs.ansible.com/ansible/latest/user_guide/playbooks_variables.html#variable-precedence-where-should-i-put-a-variable

- name: Define backup path
  set_fact:
    backup_id_path: "{{ backup_dir }}/{{ backup_id }}"

- name: Show backup id full path which will be used
  debug: msg="Using the following backup '{{ backup_id_path }}'"


- name: Ensure backup exists before proceeding
  ansible.builtin.stat:
    path: "{{ backup_id_path }}"
  register: _backup_directory
  failed_when: not _backup_directory.stat.exists

- name: Backup directory found
  ansible.builtin.debug:
    msg: "Directory {{ backup_id_path }} present"
