- name: Start dummy netbird management container without service executable
  shell:
    cmd: |
      docker compose \
        --file .ci/deploy/localenv/docker-compose.yml \
        --env-file .ci/deploy/localenv/data/secrets/.env \
        run --rm --entrypoint="" --detach --no-deps netbird-management \
        sleep infinity
    chdir: "{{ repo_dir }}"
  register: _netbird_management_id

- name: Extract container id
  set_fact:
    netbird_management_id: "{{ _netbird_management_id.stdout_lines | last }}"

- name: Restore Netbird management service
  shell:
    cmd: |
      docker exec {{ netbird_management_id }} sh -c "
        # delete old files if present
        rm -f /var/lib/netbird/*

        # delete management config that contains stored secrets
        rm /etc/netbird/management.json

        cp /var/lib/backup/{{ backup_id }}/netbird/* /var/lib/netbird/
      "

- name: Stop dummy netbird management container without service executable
  command: docker kill {{ netbird_management_id }}
  tags: always
  when: _netbird_management_id.changed
