- name: Start dummy provision container to create and mount volume
  ansible.builtin.shell:
    cmd: |
      docker compose --file .ci/deploy/localenv/docker-compose.yml run --rm --entrypoint="" --detach --no-deps provision-secrets sleep infinity
    chdir: "{{ repo_dir }}"
  register: _provision_id

- name: Extract container id
  set_fact:
    provision_id: "{{ _provision_id.stdout }}"

- name: Restore provisioning secrets
  ansible.builtin.shell:
    cmd: |
      docker cp {{ backup_id_path }}/secrets/ {{ provision_id }}:/tmp/

- name: Ensure permissions are as expected
  ansible.builtin.shell:
    cmd: |
      docker exec {{ provision_id }} sh -c "
        rm -rf /provision/*
        rsync --archive --partial --progress --delete /tmp/secrets/ /provision/

        chown -R carl:carl /provision
      "

- name: Delete old backup in volume
  ansible.builtin.shell:
    cmd: |
      docker exec {{ provision_id }} sh -c "rm -rf /backup/{{ backup_id }}"

- name: Restore backup in volume
  ansible.builtin.shell:
    cmd: |
      docker cp {{ backup_id_path }}/ {{ provision_id }}:/backup/

- name: Stop dummy provision container
  ansible.builtin.shell:
    cmd: |
      docker kill {{ provision_id }}
  tags: always                 # run always in case one of the previous steps failed
  when: _provision_id.changed  # only when it was started

- name: Start provisioning container to synchronize provision volume back to host
  ansible.builtin.shell:
    cmd: |
      docker compose --file .ci/deploy/localenv/docker-compose.yml up --build provision-secrets
    chdir: "{{ repo_dir }}"
