- name: Start dummy provision container to create and mount volume
  ansible.builtin.shell:
    cmd: |
      docker compose --file .ci/deploy/localenv/docker-compose.yml run --rm --entrypoint="" --detach --no-deps provision-secrets sleep infinity
    chdir: "{{ repo_dir }}"
  register: _provision_id

- name: Extract container id
  set_fact:
    provision_id: "{{ _provision_id.stdout }}"


- name: Delete old secrets
  ansible.builtin.shell:
    cmd: |
      docker exec {{ provision_id }} sh -c "rm -rf /provision/*"

- name: Restore provisioning secrets
  ansible.builtin.shell:
    cmd: |
      docker cp {{ backup_dir }}/{{ backup_id }}/secrets/* {{ provision_id }}:/provision/

- name: Ensure permissions are as expected
  ansible.builtin.shell:
    cmd: |
      docker exec {{ provision_id }} sh -c "chown -R carl:carl /provision"


- name: Delete old backup in volume
  ansible.builtin.shell:
    cmd: |
      docker exec {{ provision_id }} sh -c "rm -rf /backup/{{ backup_id }}/*"

- name: Restore backup in volume
  ansible.builtin.shell:
    cmd: |
      docker cp {{ backup_dir }}/{{ backup_id }}/* {{ provision_id }}:/backup/{{ backup_id }}/



- name: Stop dummy provision container
  ansible.builtin.shell:
    cmd: |
      docker kill {{ provision_id }}
