name: publish-release
on:
  workflow_call:  # allow this workflow to be called from other workflows
    inputs:
      runs-on:
        default: "['ubuntu-latest']"
        required: false
        type: string

jobs:
  publish-release:
    name: "Publish release"
    runs-on: ${{ fromJson(inputs.runs-on) }}
    permissions:
      contents: write
    env:
      artifacts_pattern: "*-${{ github.sha }}.tar.gz/*,opendut-sbom/*"
    steps:
    - name: Download Application Artifacts
      uses: actions/download-artifact@6b208ae046db98c579e8a3aa621ab581ff575935
      with:
        pattern: "*-${{ github.sha }}.tar.gz"

    - name: Download SBOM Files
      uses: actions/download-artifact@6b208ae046db98c579e8a3aa621ab581ff575935
      with:
        pattern: "opendut-sbom"

    - run: |
        cd /home/runner/work/opendut/opendut/opendut-sbom
        echo "Create ZIP with SBOM of LEA, CARL, EDGAR and CLEO into opendut-sbom.zip"
        zip opendut-sbom.zip opendut-carl-sbom.spdx.json opendut-lea-sbom.spdx.json opendut-edgar-sbom.spdx.json opendut-cleo-sbom.spdx.json
        echo "Deleting all no longer needed files with extension .spdx.json"
        find . -type f -name '*.spdx.json' -delete

    - uses: ncipollo/release-action@6c75be85e571768fa31b40abf38de58ba0397db5
      name: "Create Versioned Release"
      if: ${{ !startsWith( github.ref, 'refs/tags/canary' ) }}
      with:
        artifacts: ${{ env.artifacts_pattern }}
        body: "See the changelog for more information: https://opendut.eclipse.dev/book/changelog.html"

    - uses: ncipollo/release-action@6c75be85e571768fa31b40abf38de58ba0397db5
      name: "Create Canary Release"
      if: ${{ startsWith( github.ref, 'refs/tags/canary' ) }}
      with:
        name: ${{ github.ref_name }}
        body: "Unstable release, intended for testing."
        prerelease: true
        allowUpdates: true  # overwrite existing canary release
        artifacts: ${{ env.artifacts_pattern }}
